---
- connection: local
  hosts: localhost
  gather_facts: false
  vars:
    avi_config:
      applicationprofile:
        - name: ansible-avi-http
          tenant: admin
          state: present
          type: APPLICATION_PROFILE_TYPE_HTTP
          http_profile:
            ssl_everywhere_enabled: false
    avi_controller: sa-avicon-01.vclass.local
    avi_username: admin
    avi_password: VMware1!
  tasks:
  - name: Create Application Profile
    include_role:
      name: avinetworks.aviconfig